language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -y install mpi-default-dev gfortran python-numpy cppcheck
script:
  - cd symbiote && make 
  - cd symbiote/isosurf && make
  - cppcheck *.c
